//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServiceAssistant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Part = new HashSet<Part>();
        }
    
        public long Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> RealizationDate { get; set; }
        public string DefectDescription { get; set; }
        public long CarId { get; set; }
        public long CustomerId { get; set; }
        public long StatusId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Part> Part { get; set; }
        public virtual ServiceStatus ServiceStatus { get; set; }
    }
}
